### ISSUE TITLE
How to setup primary/secondary DNS server?

### ISSUE THREAD

**Issue by baobao1270** [bluejekyll/trust-dns#1501]
I'm trying to use trust-dns as my personal website's DNS server. Heres steps I have done:

 1. I build trust-dns with command `cargo build --release -p trust-dns --all-features`.
 2. I setup the primary server with configuration below. The parimary runs fine.
    ```toml
    listen_addrs_ipv4 = ["0.0.0.0"]
    listen_port = 53
    
    [[zones]]
    zone = "example.com"
    zone_type = "Primary"
    file = "/etc/trust-dns.d/zones/example.com.zone"
    allow_update = false
    allow_axfr = true
    enable_dnssec = true
    
    [[zones.keys]]
    key_path = "/etc/trust-dns.d/rsa_2048.zsk.pem"
    algorithm = "RSASHA512"
    password = ""
    is_zone_signing_key = true
    create_if_absent = false
    ```
 3. Now I want to create the secondary server. I noticed there is a `Secondary` value option of `zone_type` key. But I didn't see any examples of using it, nor can I find any documation. 
    ```toml
    # secondary server of example.com
    listen_addrs_ipv4 = ["0.0.0.0"]
    listen_port = 53
    
    [[zones]]
    zone = "example.com"
    zone_type = "Secondary"
    # what should I do next?
    ```

I except there is somewhere to set the address of primary server, the the secondary server can get the zone with AXFR and store in cache. When the primary server is down, the secondary server can still provide service.

Besides, I'm looking for docs for operating a trust-dns server, other than developing with libraries. Is there any docs like this?
