### ISSUE TITLE
Regression in 0.21: DoT forwarding from cloudflare doesn't work

### ISSUE THREAD

**Issue by msrd0** [bluejekyll/trust-dns#1590]
**Describe the bug**

When trying to run named as a DoT forwarder from cloudflare, no records are returned.

**To Reproduce**

Use the following config and run named with `dns-over-rustls` feature enabled:

```toml
listen_port = 5053

[[zones]]
zone = "."
zone_type = "Forward"

[zones.stores]
type = "forward"

[[zones.stores.name_servers]]
socket_addr = "1.1.1.1:853"
protocol = "tls"
tls_dns_name = "cloudflare-dns.com"
trust_nx_responses = false
```

**Expected behavior**

I expect named to return records.

**System:**
 - OS: ArchLinux
 - Version: Rolling Release
 - Architecture: amd64
 - rustc version: 1.56 (from ArchLinux repository)

**Version:**
Crate: bin
Version 0.21.0-alpha.4

**Additional context**

Log: https://gist.github.com/msrd0/4d286cbe8b4d242b89d79be541c96851

**Comment by msrd0** [comment]
**Workaround**: Add this to your config

```toml
[zones.stores.options]
try_tcp_on_error = true
```
