### ISSUE TITLE
Trustdns panic, When query non-existence domain names. (windows)

### ISSUE THREAD

**Issue by mokeyish** [bluejekyll/trust-dns#1913]
**Describe the bug**
Trustdns panic, When query non-existence domain names. (windows)

**To Reproduce**

test.conf

```toml
listen_port = 53
listen_addrs_ipv4 = ["127.0.0.1"]

[[zones]]
zone = "."
zone_type = "Forward"
stores = { type = "forward", name_servers = [
  { socket_addr = "223.5.5.5:53", protocol = "udp", trust_nx_responses = false },
  { socket_addr = "223.5.5.5:53", protocol = "tcp", trust_nx_responses = false },
] }

```

1. start trust-dns
   ```ps1
   .\target\debug\trust-dns.exe -c .\test.toml
   ```

2. query with nslookup (repeat about 10 times)
   ```ps1
   nslookup -qtype=a lan.lan.  127.0.0.1
   ```

3. trust-dns panic!!!
   ```log
   1679917039:ERROR:trust_dns:496:Trust-DNS 0.22.0 has encountered an error: unexpected close of UDP socket
   thread 'main' panicked at 'Trust-DNS 0.22.0 has encountered an error: unexpected close of UDP socket', bin\src/trust-dns.rs:497:13
   ```

**Expected behavior**
Keep running

**System:**
 - OS: Windows 11
 - Architecture: x86_64
 - Version: 11
 - rustc version: 1.65.0 (897e37553 2022-11-02), 1.68.1 (8460ca823 2023-03-20)

**Version:**
Crate: trust-dns
Version: commit 14c7424
