### ISSUE TITLE
tls and quic server works only partly

### ISSUE THREAD

**Issue by LuckyTurtleDev** [bluejekyll/trust-dns#2015]
**Describe the bug**
I have notify some strange behavior if I am hosting tls and quic  dns server using the server crate.
Dependent on the client some requested one of the protocols does not work.

|   |  tls | quic   |
|---|---|---|
| kdig  |not works  | works  |
|  crab-hole |  works | not works  |
|  android | works  | unsupported  |

kdig is a dig clone with quic, tls, https support.
[carb-hole](https://github.com/LuckyTurtleDev/crab-hole) is a pi-hole clone using trust dns (trust_dns_server::store::forwarder).

Debug output of client crab-hole instance trying to querry server crab-hole via quic (kdig --udp--> carb-hole(client) --quic-⚡-> carb-hole(server) --tls-> cloudflare).
```
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG crab_hole            > LowerQuery { name: LowerName(Name("example.com.")), original: Query { name: Name("example.com."), query_type: A, query_class: IN } }
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > No cached session for DnsName(DnsName(DnsName("dns.luckyturtle.dev")))
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > Not resuming any session
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > No cached session for DnsName(DnsName(DnsName("dns.luckyturtle.dev")))
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > Not resuming any session
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > No cached session for DnsName(DnsName(DnsName("dns.luckyturtle.dev")))
crab-hole-crab-hole-1  | 2023-09-02T13:16:57Z  ⚙️ DEBUG rustls::client::hs   > Not resuming any session
```
**To Reproduce**
```
version: '3.3'
services:
    crab-hole:
        image: 'ghcr.io/luckyturtledev/crab-hole:v0.1'
        ports:
            - "8053:8053/udp"
        environment:
            - RUST_LOG=debug
        volumes:
            - './config.toml:/data/config.toml:ro'
```

client config
```
[blocklist]
include_subdomains = true
lists = []

[[downstream]]
protocol = "udp"
listen = "[::]"
port = 8053

[[upstream.name_servers]]
socket_addr = "185.163.118.254:853"
protocol = "quic"
tls_dns_name = "dns.luckyturtle.dev"
```         

**Expected behavior**
successful request

**System:**
 - OS-Client: arch linux
 - OS-Server: Debian
 - Architecture: x86_64
 - rustc version: 1.72.0

**Version:**
Crate: server
Version: 0.23.0
