### ISSUE TITLE
Version mismatch: trust-dns-resolver 0.10.1  won't build with tls support

### ISSUE THREAD

**Issue by toreriklinnerud** [bluejekyll/trust-dns#640]
**Describe the bug**
`trust-dns-resolver 0.10.1` pulls in `trust-dns-proto ^0.6.0` and `trust-dns-rustls ^0.4.0` pulls in conflicting `trust-dns-proto ^0.5.0`

**To Reproduce**
```toml
[package]
name = "playground"
version = "0.1.0"
authors = ["tel"]

[dependencies]
trust-dns-resolver = { version = "0.10.1", features = ["dns-over-rustls"] }
```

```rust
extern crate trust_dns_resolver;

fn main() {
}
```

**Expected behavior**
Compilation success

**System:**
 - OS: macOS
 - Architecture: x86_64
 - Version 10.14.2
 - rustc version: rustc 1.30.0

**Version:**
Crate: trust-dns-resolver
Version: 0.10.1

**Additional context**
Previous version builds ("version = "= 0.10.0")
